# -*- coding: utf-8 -*-
"""Article sentiment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gcb-oKKK4Jv23wI7PTRpzZkdqxQbGv7u

###출처: https://somjang.tistory.com/entry/Keras기사-제목을-가지고-긍정-부정-중립-분류하는-모델-만들어보기 [솜씨좋은장씨]
"""

# from google.colab import drive
# drive.mount('/content/gdrive')

import codecs

positive = []
negative = []

pos = codecs.open("./positive_words.txt", 'rb', encoding='UTF-8')

while True:
    line = pos.readline()
    line = line.replace('\n', '')
    if line is '':
        break
    positive.append(line)
    if not line:
        break

pos.close()

neg = codecs.open("./negative_words.txt", 'rb', encoding='UTF-8')
while True:
    line = neg.readline()
    line = line.replace('\n', '')
    if line is '':
        break
    negative.append(line)
    if not line:
        break
neg.close()

positive

negative


def dftoCsv(my_title_df, end, datatype, date):
    my_title_df.to_csv((datatype + date + '_' + str(end) + '.csv'), sep=',', na_rep='NaN', encoding='utf-8')


import requests
from bs4 import BeautifulSoup
import re
import pandas as pd
from tqdm import tqdm


def makeDataset(start, end, datatype, date):
    labels = []
    titles = []

    latest_title = ''
    for k in tqdm(range(start, end)):
        num = k + 1

        url = "https://news.naver.com/main/list.nhn?mode=LS2D&sid2=263&sid1=101&mid=shm&date=2021" + date + "&page=" + str(
            num)

        req = requests.get(url, headers={'User-Agent': 'Mozilla/5.0'})
        html = req.text
        soup = BeautifulSoup(html, 'html.parser')

        news_sections = soup.find('div', {'class': 'list_body newsflash_body'}).find_all('ul')

        for news_section in news_sections:
            news_titles = news_section.select('dt')
            for news_title in news_titles:

                clean_title = re.sub('[-=+,#/\?:^$@*\"※~&ㆍ!』\\‘|\(\)\[\]\<\>`\'…\"\“》\r\t\n’”˚·]', '', news_title.text)
                if clean_title == '' or clean_title == '동영상기사' or clean_title == latest_title:
                    continue

                if "투자노트" in clean_title or "포토" in clean_title or "사진" in clean_title:
                    continue

                label = 0
                cnt = 0
                for i in range(len(negative)):

                    if negative[i] in clean_title:
                        label = -1
                        print("negative : ", negative[i], "clean_title : ", clean_title)
                        cnt += 1

                for i in range(len(positive)):

                    if positive[i] in clean_title:
                        label = 1
                        print("positive : ", positive[i], "clean_title : ", clean_title)
                        if cnt > 0:
                            label = 0
                            print("애매")

                latest_title = clean_title
                titles.append(clean_title)
                labels.append(label)

    my_title_df = pd.DataFrame({"title": titles, "label": labels})

    dftoCsv(my_title_df, end, datatype, date)


makeDataset(0, 89, "train", "0312")
makeDataset(0, 123, "train", "0311")
makeDataset(0, 112, "train", "0315")
makeDataset(0, 117, "test", "0310")
