"""empty message

Revision ID: 171e7afb21e9
Revises: 
Create Date: 2021-03-28 00:07:50.167138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '171e7afb21e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('title',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('title')
    op.drop_table('rank')
    # ### end Alembic commands ###
